name: E2E Test
on:
  pull_request:
    branches: [ master ]

jobs:
  e2e-test:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["12.x"]

    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci
          sudo apt update
          export DEBIAN_FRONTEND=noninteractive
          echo $DEBIAN_FRONTEND
          sudo apt install -y xvfb libgtk-3-0 libxss1 libgconf-2-4 libnss3 libasound2 netcat
          echo 'pre-req install successful'
          npm run cy:verify

      - name: Start application
        run: |
          docker-compose up -d

      - name: Run E2E test suite
        run: |
          npm run test:ci
